project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!nasa-tutorials/*.ipynb"
    - "!notebooks-data/*.ipynb"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "Machine Learning for Fisheries: Varanasi Internship 2024"
  favicon: images/incois-icon.png
  site-url: https://SAFS-Varanasi-Internship/2024-tutorials
  repo-url: https://github.com/SAFS-Varanasi-Internship/2024-tutorials
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="/images/banner.png" alt="Indian Ocean" style="width:300px"><br />Varanasi Internship (2024)
 
  sidebar:
    pinned: true
    align: center
    
    style: "docked"
    collapse-level: 1
    toc-expand: false
    contents:
      - text: "Home"
        href: index.html
      - section: "Tutorials"
        contents:
          - text: "ConvLSTM"
            href: notebooks-ml/ConvLSTM_Tutorial.ipynb
      - section: "Projects"
      - text: <img width=100px>

  navbar:
    background: primary
    search: true
    right: 
      - icon: server
        href: https://fish.opensci.live/
        text: "JupyterHub"
      - icon: wechat
        href: https://github.com/SAFS-Varanasi-Internship/Summer-2024/discussions
        text: "Discussions"
      - icon: globe
        href: https://github.com/SAFS-Varanasi-Internship
        text: "GH org"


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html

filters:
  - include-files.lua
  - quarto
