project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!nasa-tutorials/*.ipynb"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "2024 Varanasi Intern ML Projects"
  favicon: images/favicon.png
  site-url: https://SAFS-Varanasi-Internship.github.io/2024-book
  repo-url: https://github.com/SAFS-Varanasi-Internship/2024-book
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="/images/nmfs-opensci-logo.png" alt="NMFS OpenSci logo" style="width:150px"><br />NMFS OpenSci (2024
 
  sidebar:
    logo: images/uw-logo.png
    pinned: true
    align: center
    
    style: "docked"
    collapse-level: 1
    toc-expand: false
    contents:
      - section: "Welcome"
        href: index.md
        contents:
          - setup.md
          - coc.md
      - section: "Data Tutorials"
        contents:
        - section: "Earth data basics"
          contents:
            - notebooks-data/00_NASA_Earthdata_Authentication.ipynb
            - notebooks-data/02_Zarr_Access_netCDF.ipynb
        - section: "Data provider examples"
          contents:
            - notebooks-data/01_earthaccess_Downloader.ipynb
            - notebooks-data/01_ERA5_S3_Downloader.ipynb
            - notebooks-data/01_ERDDAP_Downloader.ipynb
            - notebooks-data/01_MOTU_Downloader.ipynb
        - section: "Indian Ocean Zarr"
          contents:
            - notebooks-data/02_IO_Zarr.ipynb
            - notebooks-data/04_Appending_Data.ipynb
            - notebooks-data/04_Combining_Data.ipynb
        - section: "Data viz and use"
          contents:
            - notebooks-data/02_Get_Points.ipynb
            - notebooks-data/02_Graphing_Map_Data.ipynb
            - notebooks-data/02_Xarray_hvplot.ipynb
      - section: "Machine Learning"
        contents:
        - section: "Convolutional Neural Networks"
        - section: "Tree approaches"
      - section: "Applications"
        contents:
  navbar:
    background: primary
    search: true
    right: 
      - icon: server
        href: https://fish.opensci.live/
        text: "JupyterHub"
      - icon: wechat
        href: https://github.com/SAFS-Varanasi-Internship/Summer-2024
        text: "Discussions"
      - icon: globe
        href: https://github.com/SAFS-Varanasi-Internship
        text: "GH org"
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html

filters:
  - include-files.lua
  - quarto
